# Generated by Django 4.2.5 on 2023-09-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('favorite_music', models.CharField(choices=[('Just Dance', 'Just Dance'), ('Born This Way', 'Born This Way'), ('Artpop', 'Artpop'), ('Chromatica', 'Chromatica')], max_length=50)),
                ('biography', models.TextField()),
            ],
        ),
    ]
